version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Build Docker image
          command: docker-compose build
      - run:
          name: Run Docker Compose
          command: docker-compose up -d
      - run:
          name: Run integration tests
          command: pytest integration_tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build